<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EvitaCoffee.Domain\EvitaCoffee.Domain.csproj" />
    <ProjectReference Include="..\EvitaCoffee.Contracts\EvitaCoffee.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DependencyInjection\" />
    <Folder Include="DTOs\" />
    <Folder Include="Helpers\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Options\" />
    <Folder Include="Services\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
